#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[0;32m'
CYAN='\033[0;36m'
NO_COLOR='\033[0m'

if [ -n "$(git status --porcelain)" ]; then
  if [ -n "$(git status --porcelain -- '*.ts' '*.tsx')" ]; then
    echo "${CYAN}→${NO_COLOR} Running TypeScript compiler..."
    cd src/client && npx tsc &
    cd src/server && npx tsc
    wait
    cd ../../
  fi

  echo "${CYAN}→${NO_COLOR} Running lint-staged..."
  npx lint-staged

  echo "${GREEN}Success!${NO_COLOR}"
fi
